repos:
  - repo: local
    hooks:
      - id: commitlint
        name: Conventional Commits Checker
        description: Checks commits for conventional commits format, requires github.com/conventionalcommit/commitlint
        language: system
        entry: make lint-commits
        stages:
          - commit-msg

      - id: golangci-lint
        name: Go Linter
        description: Runs `golangci-lint`, requires github.com/golangci/golangci-lint
        language: system
        entry: make lint
        files: '(?<!\.pb)\.go$'
        stages:
          - commit
